-- ============================================================================
-- SQL PORTFOLIO: EXERCISE 08 - GEOGRAPHIC INSIGHTS
-- ============================================================================
-- OBJECTIVE: Analyze regional patterns, logistics performance, and market opportunities
-- SKILLS: Geographic analysis, regional comparisons, logistics optimization, market penetration
-- BUSINESS CONTEXT: Geographic analysis drives expansion decisions, logistics optimization,
--                   and regional marketing strategies
-- ============================================================================

-- ============================================================================
-- QUESTION 1: State-Level Market Analysis
-- ============================================================================
-- Business Question: How do different Brazilian states perform as markets?
-- Write a query to analyze state-level performance:
-- - State code and name
-- - Number of customers
-- - Number of sellers
-- - Total orders
-- - Total revenue
-- - Average order value
-- - Market share (% of total revenue)
-- - Customer density (customers per capita equivalent)
-- - Revenue per customer
-- - Seller-to-customer ratio
-- Sort by total revenue (highest first)
-- Show top 15 states

-- Your SQL query here:




-- ============================================================================
-- QUESTION 2: City-Level Performance Analysis
-- ============================================================================
-- Business Question: Which cities are our key markets?
-- Write a query to analyze city-level metrics:
-- - City and state
-- - Customer count
-- - Total orders
-- - Total revenue
-- - Average order value
-- - Number of unique products ordered
-- - Market penetration (orders per customer)
-- - Revenue concentration (% of state's revenue)
-- - Growth potential indicator
-- Include only cities with at least 100 customers
-- Sort by revenue (highest first)
-- Show top 20 cities

-- Your SQL query here:




-- ============================================================================
-- QUESTION 3: Regional Logistics Performance
-- ============================================================================
-- Business Question: How does delivery performance vary by region?
-- Write a query to analyze logistics by state:
-- - Customer state
-- - Number of delivered orders
-- - Average delivery time (days)
-- - Fastest delivery time
-- - Slowest delivery time
-- - Percentage of orders delivered within 7 days
-- - Percentage of orders delivered within 14 days
-- - Delivery performance rating:
--   * Excellent: < 10 days average
--   * Good: 10-15 days average
--   * Poor: > 15 days average
-- Sort by average delivery time (fastest first)

-- Your SQL query here:




-- ============================================================================
-- QUESTION 4: Seller Geographic Distribution
-- ============================================================================
-- Business Question: Where are our sellers located and how do they perform?
-- Write a query to analyze seller distribution:
-- - Seller state
-- - Number of sellers
-- - Total revenue generated by sellers in this state
-- - Average revenue per seller
-- - Number of customers served
-- - Geographic reach (number of states they sell to)
-- - Seller density (sellers per market size)
-- - Performance rating (revenue per seller vs. national average)
-- Sort by total revenue (highest first)

-- Your SQL query here:




-- ============================================================================
-- QUESTION 5: Interstate Commerce Analysis
-- ============================================================================
-- Business Question: How does commerce flow between states?
-- Write a query to analyze interstate trade:
-- - Seller state
-- - Customer state
-- - Number of orders
-- - Total revenue
-- - Average order value
-- - Top product categories traded
-- - Distance category (same state, neighboring state, distant state)
-- - Trade flow intensity (revenue / geographic distance proxy)
-- Include only combinations with at least 50 orders
-- Sort by total revenue (highest first)

-- Your SQL query here:




-- ============================================================================
-- QUESTION 6: Market Penetration Analysis
-- ============================================================================
-- Business Question: Which regions have growth opportunities?
-- Write a query to identify market penetration:
-- - State
-- - Population proxy (customer count)
-- - Market penetration (orders per customer)
-- - Revenue per capita (revenue per customer)
-- - Average order frequency
-- - Market maturity classification:
--   * Mature: High penetration, high frequency
--   * Growing: Medium penetration, increasing frequency
--   * Emerging: Low penetration, low frequency
-- - Growth opportunity score
-- Sort by growth opportunity score (highest first)

-- Your SQL query here:




-- ============================================================================
-- QUESTION 7: Product Category by Region
-- ============================================================================
-- Business Question: How do product preferences vary by region?
-- Write a query to analyze regional product preferences:
-- - Customer state
-- - Product category
-- - Total quantity sold
-- - Total revenue
-- - Market share within state
-- - National market share for comparison
-- - Regional preference index (state share / national share)
-- - Category rank within state
-- Values > 1.0 indicate above-average preference
-- Sort by state, then by regional preference index

-- Your SQL query here:




-- ============================================================================
-- QUESTION 8: Shipping Cost Analysis
-- ============================================================================
-- Business Question: How do shipping costs vary by distance and region?
-- Write a query to analyze shipping economics:
-- - Customer state
-- - Average shipping cost
-- - Average order value
-- - Shipping cost as % of order value
-- - Number of orders
-- - Total shipping revenue
-- - Shipping efficiency (order value / shipping cost)
-- - Distance-based shipping tier:
--   * Local: Same state as major sellers
--   * Regional: Neighboring states
--   * National: Distant states
-- Sort by shipping cost percentage (highest first)

-- Your SQL query here:




-- ============================================================================
-- QUESTION 9: Geographic Customer Segments
-- ============================================================================
-- Business Question: How do customer segments vary geographically?
-- Write a query to analyze geographic customer segmentation:
-- - State
-- - Customer value tier (based on total spent)
-- - Number of customers in each tier
-- - Average order value by tier
-- - Geographic concentration index
-- - Tier distribution (% of state's customers)
-- - Comparison to national tier distribution
-- - Market opportunity by tier
-- Group by state and customer tier
-- Sort by state, then by customer tier

-- Your SQL query here:




-- ============================================================================
-- QUESTION 10: Seasonal Geographic Patterns
-- ============================================================================
-- Business Question: How do seasonal patterns vary by region?
-- Write a query to analyze seasonal geographic differences:
-- - Customer state
-- - Season (Q1, Q2, Q3, Q4)
-- - Total orders
-- - Total revenue
-- - Seasonal index (season revenue / quarterly average)
-- - Peak season identification
-- - Seasonal volatility (coefficient of variation)
-- - Weather/climate correlation opportunities
-- Group by state and season
-- Sort by state, then by seasonal index

-- Your SQL query here:




-- ============================================================================
-- QUESTION 11: Market Expansion Opportunities
-- ============================================================================
-- Business Question: Which regions present the best expansion opportunities?
-- Write a query to identify expansion opportunities:
-- - State
-- - Current market metrics:
--   * Customer count
--   * Revenue
--   * Average order value
-- - Market potential indicators:
--   * Revenue per customer vs. national average
--   * Order frequency vs. national average
--   * Category diversity index
-- - Competition intensity (sellers per customer)
-- - Expansion priority score
-- - Recommended expansion strategy
-- Sort by expansion priority score (highest first)

-- Your SQL query here:




-- ============================================================================
-- QUESTION 12: Regional Performance Dashboard
-- ============================================================================
-- Business Question: What are the key metrics for regional performance monitoring?
-- Write a query to create a regional dashboard:
-- - State
-- - Current month metrics:
--   * Orders
--   * Revenue
--   * New customers
--   * Average delivery time
-- - Year-over-year growth:
--   * Order growth
--   * Revenue growth
--   * Customer growth
-- - Performance indicators:
--   * Market share
--   * Delivery performance
--   * Customer satisfaction (avg review score)
-- - Regional ranking (1-27 for Brazilian states)
-- - Status indicator (growing/stable/declining)
-- Sort by regional ranking

-- Your SQL query here:




-- ============================================================================
